# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20190216_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
